### ISSUE TITLE
Keyword `require` is undefined

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/babel-engine-plugin#1]
Apparently I'm listening to the wrong compilation step because this plugin somehow gets `require` calls in your bundle instead of the `__webpack_require` function.

**Comment by SamVerschueren** [comment]
@TheLarkInn Could you give any tips on what I should do in order to solve this? Currently I use the [`succeed-module`](https://github.com/SamVerschueren/babel-engine-plugin/blob/master/index.js#L15) event. I also tried with the `build-module` event and with manually reading the source like this

```js
const source = fs.readFileSync(m.resource, 'utf8');

const result = babel.transform(source, this._options);

m.source = () => result.code;
```

But I always get the usual `require` statements instead of the custom `__webpack_require`. I'm pretty new to this plugin development thing so any tips are more than welcome!

**Comment by TheLarkInn** [comment]
@SamVerschueren The __webpack_require__ doesn't get stripped out until after the seal event. You would really want to hook into post rendering of chunkTemplates and dependencyTemplates

**Comment by SamVerschueren** [comment]
I don't think I totally understand what you are saying. As I said, I'm quite new to this and the docs does't really seem to provide me with enough information.

So what I want to do is transform the source code of a dependency depending on `engines.node` property of the `package.json` of that dependency. That's why I can't use a loader here.

The plugin is pretty basic as you can see [here](https://github.com/SamVerschueren/babel-engine-plugin/blob/master/index.js) but it's not working as intended. Probably because I'm at the wrong phase of all the steps that has to be performed.

---------------------
I also looked into your answer about the `dependencyTemplates`. I noticed that I can find them in the `compilation` object. But when I log them in the `make` phase like this

```js
compiler.run('make', compilation => {
     console.log(compilation.dependencyTemplates);
});
```

I don't really get helpfull information as it's a map of constructors that doesn't give me back anything usefull.

Sorry for all the questions though. Like I said, pretty new to Webpack and the plugin system.

**Comment by SamVerschueren** [comment]
I managed to get it working. Not sure if this is the way to do it but now I'm configuring a custom module template that does what I want.
