### ISSUE TITLE
babel-engine-plugin not respecting/reading .babelrc

### ISSUE THREAD

**Issue by thasmo** [SamVerschueren/babel-engine-plugin#7]
It seems that `babel-engine-plugin` does not use/read the contents of the project's `.babelrc` file.
Is this intended and has certain reasons?

**Comment by thasmo** [comment]
After reading https://babeljs.io/docs/usage/api/#options I believe `.babelrc` should be used anyway and that the issue is probably not created by `babel-engine-plugin`. I'll have to take a closer look soon.

**Comment by SamVerschueren** [comment]
Feel free to send a PR if you found the root cause. Happy to merge it in.

**Comment by thasmo** [comment]
I think my `.babelrc` configuration was faulty somehow and it actually works, when I recall correctly. I'll reopen if I still encounter the problem.

**Comment by SamVerschueren** [comment]
Thanks!
