### ISSUE TITLE
Less verbose logging

### ISSUE THREAD

**Issue by thasmo** [SamVerschueren/babel-engine-plugin#8]
Currently the warning messages `WARNING in The package `...` doesn't specify the targeted Node.js version in its package.json `engines` field. Open an issue and ask them to do it, or even better, do a pull request.` are being printed on every compilation-run when running webpack with `--watch`, which prints a lot of messages and pollutes the console window.

Is there currently a way to have a less verbose logging or print the warnings only once?

**Comment by SamVerschueren** [comment]
No there is not. We could keep track of which error already was printed and do not print it twice.

**Comment by SamVerschueren** [comment]
I added a second `pluginOptions` object in `0.2.0` where you can set `verbose: false`.

```js
new BabelEnginePlugin({
    presets: ['env']
}, {
    verbose: false
})
```

This should only print the error once. At least I hope it does, was unable to test it. Feel free to provide feedback!

**Comment by timwis** [comment]
Hmm..i'm still getting all the warnings. Did you perhaps mean to use an `||` operator instead of `&&` on [this line](https://github.com/SamVerschueren/babel-engine-plugin/blob/master/lib/babel-module-template.js#L20)?

**Comment by SamVerschueren** [comment]
No, because it should not print the logs if the `verbose` option is explicitly set to `false` AND the package is already part of the `logs` Set. Not sure why it still logs it. Are you able to debug this on your end by adding some debugging logs to `node_modules/babel-engine-plugins/index.js` directly? If not, I will see if I find the time to take a look at it.

**Comment by mnemanja** [comment]
@SamVerschueren I'm on the version 0.2.1 and experiencing the same thing. 

![screen shot 2018-05-22 at 09 48 47](https://user-images.githubusercontent.com/1423218/40348944-60737998-5da5-11e8-95c1-27e1d445b513.png)

**Comment by SamVerschueren** [comment]
Would be nice if someone is able to debug this

> Are you able to debug this on your end by adding some debugging logs to node_modules/babel-engine-plugins/index.js directly? If not, I will see if I find the time to take a look at it.
